import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import LogoMain from '../components/LogoMain';
import MainSiteCards from '../components/MainSiteCards';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main>
        <div className="grid grid-cols-2 mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-36 mb-24">
          <div className="sm:text-center md:text-left">
            <h1 className="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
              <span className="block xl:inline">Centrum Usług</span>{' '}
              <span className="block text-indigo-600">Motoryzacyjnych</span>
            </h1>
            <p className="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">
              Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet
              fugiat veniam occaecat fugiat aliqua.
            </p>
            <div className="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-start">
              <div className="rounded-md">
                <a
                  href="#"
                  className="inline-block px-8 py-3 text-xl font-medium text-white transition bg-indigo-600 rounded hover:scale-110 hover:shadow-xl active:bg-indigo-500 focus:outline-none focus:ring"
                >
                  Skontaktuj się z nami!
                </a>
              </div>
            </div>
          </div>
          <div className="">
            <LogoMain/>
          </div>
        </div>
        <h2 className="mt-64 text-4xl text-center tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
          <span className="block xl:inline">Nasze usługi</span>
        </h2>
        <MainSiteCards/>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
